package excecao;

public class ExcecaoCausadora {

    public static void main(String[] args) {

	metodoA(null);
    }

    static void metodoA(Aluno aluno) {

	try {
	    metodoB(aluno);
	} catch (Exception e) {
	    // TODO Auto-generated catch block
	    e.printStackTrace();
	}
    }

    static void metodoB(Aluno aluno) {
	if (aluno == null) {
	    throw new NullPointerException("ERRO: O aluno est√° nulo!");
	}

	System.out.println(aluno.nome);
    }
}
